name: Deploy to Production
on:
  push:
    branches: [ "master" ]
jobs:
  versions:
    runs-on: ubuntu-latest
    outputs:
      publised: ${{ steps.versions.outputs.published }}
      package: ${{ steps.versions.outputs.package }}
    steps:
    - uses: actions/setup-node@v4
    - uses: actions/checkout@v4.1.1
    - id: versions
      run: |
        echo "published=$(npm view @yucacodes/ui version)" >> "$GITHUB_OUTPUT"
        echo "package=$(cat package.json | jq -r '.version')" >> "$GITHUB_OUTPUT"

  build:
    needs: versions
    runs-on: ubuntu-latest
    if: ${{ jobs.versions.outputs.publised != jobs.versions.outputs.package }}
    steps:
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Front Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        tags: yucacodes/ui-front:${{ github.sha }}
        push: true
        target: front
    - name: Deploy
      uses: appleboy/ssh-action@v1.0.1
      with:
        host: ui.yuca.codes
        username: deployer
        key: ${{ secrets.DEPLOYER_USER_KEY }}
        script: |
          docker run -d --restart=unless-stopped -e VIRTUAL_HOST=ui.yuca.codes -e LETSENCRYPT_HOST=ui.yuca.codes yucacodes/ui-front:${{ github.sha }}
          CONTAINERS_TO_STOP=$(docker ps --format '{{.ID}} {{.Image}}' | grep yucacodes/ui-front | grep -v ${{ github.sha }} | awk '{ print $1 }')
          for C in $CONTAINERS_TO_STOP; do docker kill $C; done;
          for C in $CONTAINERS_TO_STOP; do docker rm $C; done;
          docker image prune --all --force
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - run: docker build . --file Dockerfile --tag publish-lib --target=publish-lib
    - run: docker run -e NPM_TOKEN=${{ secrets.NPM_TOKEN }} publish-lib 