name: Test Raw commands
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: ls -la ${{ github.action_path }}
    - run: docker build ${{ github.action_path }} --file ${{ github.action_path }}/Dockerfile --tag publish-lib  --target=publish-lib 
    - run: docker run publish-lib
